export default {
  login: "haze355",
  id: 43584213,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/haze355",
  html_url: "https://github.com/haze355",
  followers_url: "https://api.github.com/users/haze355/followers",
  following_url: "https://api.github.com/users/haze355/following{/other_user}",
  gists_url: "https://api.github.com/users/haze355/gists{/gist_id}",
  starred_url: "https://api.github.com/users/haze355/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/haze355/subscriptions",
  organizations_url: "https://api.github.com/users/haze355/orgs",
  repos_url: "https://api.github.com/users/haze355/repos",
  events_url: "https://api.github.com/users/haze355/events{/privacy}",
  received_events_url: "https://api.github.com/users/haze355/received_events",
  type: "User",
  site_admin: false,
  name: "Yiming Zhang",
  company: "PSU",
  blog: "www.yimingzhang.com",
  location: "Portland",
  email: null,
  hireable: null,
  bio: "PSU CS Graduate student",
  twitter_username: "haze355",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
